### ISSUE TITLE
Users can not select single item in Data Query results

### ISSUE THREAD

**Issue by Renekton** [zilliztech/attu#42]
**Describe the bug:**
Users can not select single item in Data Query results

**Steps to reproduce:**
1. Query data in collection, find results as shown in the figure below：
![image](https://user-images.githubusercontent.com/7531084/157389326-3709d5f9-bd5a-4c0d-bc71-69a739097bcb.png)

2. Clik the button, select single item
![image](https://user-images.githubusercontent.com/7531084/157389913-fb6d88a2-8072-47fc-8077-9282cc188422.png)

3. All options are selected
![1646809598(1)](https://user-images.githubusercontent.com/7531084/157390116-f1ae4dae-b5b4-429e-b405-264a0925cd9f.png)
Users can not select single item.

**Attu version:**
v1.22.10

**Attu version:**

**Comment by czhen-zilliz** [comment]
Hi, @Renekton , I cannot reproduce the issue.
Could you download the [latest Attu](https://github.com/zilliztech/attu/releases/latest) v2.0.4 and try again?
I think this issue had been fixed in latest release.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/83751452/157400713-8804f80f-6828-4210-bb3a-ad395d6a8ba6.png">

**Comment by Renekton** [comment]
> v1.22.10

How to check the version of Attu ？ I run the commad "docker logs #zttu container Id#", and check the version in logs, the log shows that the version is v1.22.10

![image](https://user-images.githubusercontent.com/7531084/157416839-c60c542c-503a-4f98-adef-7ec61f2d8169.png)

**Comment by czhen-zilliz** [comment]
Hi @Renekton ,

1. Pull latest image again by run `docker pull zilliz/attu:latest`.(Or you can pull by specified tag `docker pull zilliz/attu:v2.0.4`)
2. Terminate and delete your current container by ID `docker stop {your_attu_container_id}` `docker rm {your_attu_container_id}` 
3. Run attu `docker run -p 3000:3000 --name myAttu -d zilliz/attu:latest` (Or ``docker run -p 3000:3000 --name myAttu -d zilliz/attu:v2.0.4``)

Then the Attu version will show on the bottom of left navigation after login.
<img width="125" alt="image" src="https://user-images.githubusercontent.com/83751452/157423472-0f46a0a3-5cf3-446a-8b7e-b9d86204da7a.png">

**Comment by Renekton** [comment]
I have upgraded the version to v 2.0.4, and the problem remains in chrome and edge browser.

![image](https://user-images.githubusercontent.com/7531084/157586221-a19cfec8-d128-4cd8-b2f0-e975ed4da340.png)

**Comment by czhen-zilliz** [comment]
I created a similar collection, and I cannot reproduce the issue.
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/83751452/157797680-30035d3c-d138-4a24-a1e0-081acf8e34b2.png">

So, could you please provide more details? Such as collection schema, example rows and browser console logs?
I wonder if any error/warning messages printed on browser console.

**Comment by Renekton** [comment]
collection schema :
![image](https://user-images.githubusercontent.com/7531084/157798679-b3c87337-f2e5-4655-a69d-ede0a1d01ac5.png)

How to get browser console logs ？

**Comment by czhen-zilliz** [comment]
Hi @Renekton , I successfully reproduce the issue.
We find that the issue occurs when primary field name is all uppercase.
We will take more investigations, and any updates will let you know asap.
